name: petri
version: 0.1.0.0
github: "willGuimont/petri"
license: BSD3
author: "William Guimont-Martin"
maintainer: "william.guimont-martin.1@ulaval.ca"
copyright: "2020 William Guimont-Martin"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/willGuimont/petri#readme>

ghc-options:
  - -Wall
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wcompat
  - -Widentities
  - -Wredundant-constraints
  - -Wmissing-export-lists
  - -Wpartial-fields
  - -fhide-source-paths
  - -freverse-errors

default-extensions:
  - ApplicativeDo
  - RecordWildCards

dependencies:
  - base >= 4.7 && < 5
  - containers
  - lens

library:
  source-dirs: src

executables:
  petri-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - petri

tests:
  petri-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - petri
      - hspec
      - QuickCheck
